from typing import List

from back_webconn_file_creation.keys.keys import Key


class User:
    def __init__(self, __id: int, name: str, email: str, password: str, __keys: List[int]) -> None:
        self._id = ...
        self.name = ...
        self.email = ...
        self.password = ...
        self._keys = ...

    def add_key(self, key: Key) -> None: ...

    def remove_key(self, key: Key) -> None: ...

    def keys(self) -> List[Key]: ...