<ImageButton@ButtonBehavior+Image>

<Game_GUI>:
    FloatLayout:
        ImageButton:
            size_hint: [0.2, 0.2]
            source: "C:\\Users\\kanna\\Pictures\\OpenCity-Main_Menu\\PNG\\Build-Icon.png"
            on_press:
                self.source = "C:\\Users\\kanna\\Pictures\\OpenCity-Main_Menu\\PNG\\Build-Icon_Click.png"
            on_release:
                self.source = "C:\\Users\\kanna\\Pictures\\OpenCity-Main_Menu\\PNG\\Build-Icon.png"
