from back_webconn_file_creation.users.users import User


class Key:
    def __init__(self, __id: int, __key: str, __type: str, _user: int) -> None:
        self.id_ = ...
        self._key = ...
        self._type = ...
        self._user_id = ...

    @property
    def owner(self) -> User: ...
